// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQmvmRdygSOEBwPyrc5hXY4S9DiG-9Cgs',
    appId: '1:276266732573:web:0bbdc7cdf6772ac3c8caf4',
    messagingSenderId: '276266732573',
    projectId: 'solarpumpsupervision',
    authDomain: 'solarpumpsupervision.firebaseapp.com',
    storageBucket: 'solarpumpsupervision.firebasestorage.app',
    measurementId: 'G-30355MX842',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgE7z0FDDq6MXowvQAzjV6cvwpQxGdnJ4',
    appId: '1:276266732573:android:13ff06a1f57ccf2bc8caf4',
    messagingSenderId: '276266732573',
    projectId: 'solarpumpsupervision',
    storageBucket: 'solarpumpsupervision.firebasestorage.app',
    databaseURL: 'https://solarpumpsupervision-b0c86-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQmvmRdygSOEBwPyrc5hXY4S9DiG-9Cgs',
    appId: '1:276266732573:web:c525969c8cc955dfc8caf4',
    messagingSenderId: '276266732573',
    projectId: 'solarpumpsupervision',
    authDomain: 'solarpumpsupervision.firebaseapp.com',
    storageBucket: 'solarpumpsupervision.firebasestorage.app',
    measurementId: 'G-B7LXQLRZ2J',
  );
}

